# Generated by Django 5.1.2 on 2025-02-18 10:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchNetwork',
            fields=[
                ('sys_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('CostCenter', models.CharField(max_length=5, unique=True)),
                ('Active', models.BooleanField(default=True)),
                ('BranchName', models.CharField(max_length=100)),
                ('MandantID', models.CharField(max_length=50)),
                ('RegionID', models.CharField(max_length=50)),
                ('RegionName', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Latitude', models.CharField()),
                ('Longitude', models.CharField()),
                ('State', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=100)),
                ('PostCode', models.CharField(max_length=10)),
                ('BranchOperator', models.CharField(max_length=4)),
                ('BranchMainType', models.CharField(max_length=100)),
                ('AssemblyPoint', models.CharField(null=True)),
                ('PoisonEmergencyCallNumber', models.CharField(null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
