# Generated by Django 5.1.6 on 2025-02-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnterpriseProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchnetwork',
            name='BranchOperator',
            field=models.CharField(max_length=50),
        ),
    ]
