# Generated by Django 5.1.6 on 2025-02-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnterpriseProfile', '0002_alter_branchnetwork_branchoperator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchnetwork',
            name='AssemblyPoint',
            field=models.CharField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branchnetwork',
            name='PoisonEmergencyCallNumber',
            field=models.CharField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
