# Generated by Django 5.2.1 on 2025-05-21 07:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EnterpriseProfile', '0003_alter_branchnetwork_assemblypoint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('sys_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ContactPersonName', models.CharField(max_length=255)),
                ('ContactPersonPhoneNumber', models.CharField(blank=True, max_length=255)),
                ('ContactPersonEmail', models.EmailField(blank=True, max_length=254)),
                ('ContactType', models.IntegerField(choices=[(1, 'Emergency'), (2, 'Non-Emergency'), (3, 'Internal'), (4, 'External')])),
                ('RelatedBranch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnterpriseProfile.branchnetwork')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alarmplan',
            fields=[
                ('sys_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('Active', models.BooleanField(default=True)),
                ('RelatedBranch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnterpriseProfile.branchnetwork')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('contactPerson', models.ManyToManyField(to='Alarmplan.contactperson')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
