# Generated by Django 5.2.5 on 2025-09-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alarmplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmplan',
            name='AssemblyPoint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alarmplan',
            name='PoisonEmergencyHotline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
