# Generated by Django 5.1.2 on 2024-10-16 10:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAidRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('IncidentDateTime', models.DateTimeField()),
                ('TypeOfIncident', models.IntegerField(choices=[(1, 'Commute'), (2, 'Workplace')])),
                ('IncidentLocation', models.JSONField()),
                ('InjuryOccurence', models.BooleanField(default=False)),
                ('AccidentWitness', models.JSONField()),
                ('AffectedBodyParts', models.JSONField()),
                ('UsedBandageMaterial', models.JSONField()),
                ('AccidentCause', models.IntegerField(choices=[(1, 'Damaged Furniture'), (2, 'Emergency exits blocked'), (3, 'Falling object'), (4, 'Inadequate lighting'), (5, 'Loose cables'), (6, 'Obstructed path'), (7, 'Slippery floors'), (8, 'Tripping Hazard'), (9, 'Unsecured floor opening'), (10, 'Unstable shelving')])),
                ('PersonalProtectiveEquipment', models.IntegerField(choices=[(1, 'Test')])),
                ('WorkContunuation', models.BooleanField()),
                ('RequestedFor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
