# Generated by Django 5.1.2 on 2024-10-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalFirstAid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstaidrecord',
            old_name='WorkContunuation',
            new_name='WorkContinuation',
        ),
        migrations.AddField(
            model_name='firstaidrecord',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
