# Generated by Django 5.1.2 on 2024-10-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalFirstAid', '0002_rename_workcontunuation_firstaidrecord_workcontinuation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstaidrecord',
            name='IncidentLocation',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='firstaidrecord',
            name='InjuryOccurence',
            field=models.BooleanField(default=True),
        ),
    ]
