# Generated by Django 5.1.2 on 2024-10-17 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalFirstAid', '0003_alter_firstaidrecord_incidentlocation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstaidrecord',
            name='AccidentWitness',
        ),
        migrations.RemoveField(
            model_name='firstaidrecord',
            name='AffectedBodyParts',
        ),
        migrations.RemoveField(
            model_name='firstaidrecord',
            name='UsedBandageMaterial',
        ),
    ]
