# Generated by Django 5.1.2 on 2024-10-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalFirstAid', '0004_remove_firstaidrecord_accidentwitness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstaidrecord',
            name='AccidentDescription',
            field=models.TextField(default='No description given'),
        ),
        migrations.AddField(
            model_name='firstaidrecord',
            name='AccidentWitness',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='firstaidrecord',
            name='FirstAidMeasures',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='firstaidrecord',
            name='PersonalProtectiveEquipment',
            field=models.IntegerField(choices=[(1, 'Gloves'), (2, 'Glasses'), (3, 'High-Visibility West'), (4, 'Mask'), (5, 'Safety Shoes'), (6, 'Hard Hat'), (7, 'Hearing Protection')]),
        ),
    ]
