# Generated by Django 5.1.2 on 2024-10-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalFirstAid', '0005_firstaidrecord_accidentdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstaidrecord',
            name='AccidentDescription',
            field=models.TextField(),
        ),
    ]
