# Generated by Django 5.1.2 on 2024-10-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalFirstAid', '0006_alter_firstaidrecord_accidentdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstaidrecord',
            name='IncidentLocation',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='firstaidrecord',
            name='InjuryOccurence',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='firstaidrecord',
            name='PersonalProtectiveEquipment',
            field=models.IntegerField(choices=[(0, 'No Equipment'), (1, 'Gloves'), (2, 'Glasses'), (3, 'High-Visibility West'), (4, 'Mask'), (5, 'Safety Shoes'), (6, 'Hard Hat'), (7, 'Hearing Protection')], null=True),
        ),
    ]
