# Generated by Django 5.1.2 on 2024-10-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalFirstAid', '0007_alter_firstaidrecord_incidentlocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstaidrecord',
            name='AccidentWitness',
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firstaidrecord',
            name='FirstAidMeasures',
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firstaidrecord',
            name='PersonalProtectiveEquipment',
            field=models.IntegerField(blank=True, choices=[(0, 'No Equipment'), (1, 'Gloves'), (2, 'Glasses'), (3, 'High-Visibility West'), (4, 'Mask'), (5, 'Safety Shoes'), (6, 'Hard Hat'), (7, 'Hearing Protection')], null=True),
        ),
    ]
