# Generated by Django 5.1.2 on 2024-10-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalFirstAid', '0008_alter_firstaidrecord_accidentwitness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstaidrecord',
            name='AccidentCause',
            field=models.IntegerField(choices=[(1, 'Damaged Furniture'), (2, 'Emergency exits blocked'), (3, 'Falling object'), (4, 'Inadequate lighting'), (5, 'Loose cables'), (6, 'Obstructed path'), (7, 'Slippery floors'), (8, 'Tripping Hazard'), (9, 'Unsecured floor opening'), (10, 'Unstable shelving')], verbose_name='What caused the accident?'),
        ),
        migrations.AlterField(
            model_name='firstaidrecord',
            name='AccidentDescription',
            field=models.TextField(verbose_name='Please describe the incident'),
        ),
        migrations.AlterField(
            model_name='firstaidrecord',
            name='AccidentWitness',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='firstaidrecord',
            name='FirstAidMeasures',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='firstaidrecord',
            name='IncidentDateTime',
            field=models.DateTimeField(verbose_name='When did the incident occur?'),
        ),
        migrations.AlterField(
            model_name='firstaidrecord',
            name='IncidentLocation',
            field=models.JSONField(default=dict, verbose_name='Where did the incident occur?'),
        ),
        migrations.AlterField(
            model_name='firstaidrecord',
            name='InjuryOccurence',
            field=models.BooleanField(verbose_name='Did the incident result in an injury?'),
        ),
        migrations.AlterField(
            model_name='firstaidrecord',
            name='PersonalProtectiveEquipment',
            field=models.IntegerField(blank=True, choices=[(0, 'No Equipment'), (1, 'Gloves'), (2, 'Glasses'), (3, 'High-Visibility West'), (4, 'Mask'), (5, 'Safety Shoes'), (6, 'Hard Hat'), (7, 'Hearing Protection')], null=True, verbose_name='What protective equipment was used?'),
        ),
        migrations.AlterField(
            model_name='firstaidrecord',
            name='TypeOfIncident',
            field=models.IntegerField(choices=[(1, 'Commute'), (2, 'Workplace')], verbose_name='Did the incident occur during commute or at the workplace?'),
        ),
        migrations.AlterField(
            model_name='firstaidrecord',
            name='WorkContinuation',
            field=models.BooleanField(verbose_name='Was work continued after the incident?'),
        ),
    ]
