# Generated by Django 5.1.2 on 2024-10-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalFirstAid', '0009_alter_firstaidrecord_accidentcause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstaidrecord',
            name='TypeOfIncident',
            field=models.IntegerField(choices=[(1, 'Commute'), (2, 'Workplace')], verbose_name='Did the incident occur duringcommute or at the workplace?'),
        ),
    ]
