# Generated by Django 5.1.2 on 2025-02-18 10:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalFirstAid', '0010_alter_firstaidrecord_typeofincident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstaidrecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='firstaidrecord',
            name='sys_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
